apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-init
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        email VARCHAR (255) UNIQUE NOT NULL,
        password VARCHAR (255) NOT NULL
    );
    INSERT INTO users (email, password) VALUES ('tjmars.yt@gmail.com', '123456') ON CONFLICT (email) DO NOTHING;
