apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "invoiceapp.fullname" . }}-config
  labels:
    {{- include "invoiceapp.labels" . | nindent 4 }}
data:
  # PostgreSQL configuration
  DATABASE_HOST: {{ .Values.config.database.host | quote }}
  DATABASE_NAME: {{ .Values.config.database.name | quote }}
  DATABASE_USER: {{ .Values.config.database.user | quote }}
  
  # RabbitMQ configuration
  RABBITMQ_HOST: {{ .Values.config.rabbitmq.host | quote }}
  RABBITMQ_USER: {{ .Values.config.rabbitmq.user | quote }}
  INVOICE_QUEUE: {{ .Values.config.rabbitmq.invoiceQueue | quote }}
  NOTIFICATION_QUEUE: {{ .Values.config.rabbitmq.notificationQueue | quote }}
  
  # Email configuration
  EMAIL_SENDER: {{ .Values.config.email.sender | quote }}
