apiVersion: v1
kind: Service
metadata:
  name: {{ include "invoiceapp.fullname" . }}-auth
  labels:
    app: auth
    {{- include "invoiceapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: auth
    {{- include "invoiceapp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "invoiceapp.fullname" . }}-gateway
  labels:
    app: gateway
    {{- include "invoiceapp.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: gateway
    {{- include "invoiceapp.selectorLabels" . | nindent 4 }}
